databases:
  - name: employeesystem-db
    databaseName: employeesystem
    user: employeesystem
    plan: free

services:
  - type: web
    name: employeesystem
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ApplyMigrations
        value: "true"
      - key: DatabaseProvider
        value: Postgres
      - key: SeedDefaultUsers
        value: "true"
      - key: SeedSampleData
        value: "true"
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: employeesystem-db
          property: connectionString
